name: docker-controller

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  build:
    name: docker-controller
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set parameters
        id: parameters
        run: |
          SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
          IMAGE_NAME=${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/docker-build-artifacts/controller
          IMAGE_TAG=commit-${SHORT_SHA}
          IMAGE_URL=${IMAGE_NAME}:${IMAGE_TAG}
          echo "::set-output name=image_url::${IMAGE_URL}"

      - name: Authenticate against Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_BUILD_ARTIFACT_UPLOADER_SERVICE_ACCOUNT_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Test if image already exists
        id: image_exists
        run: |
          # Detect whether the image already exists
          # If it does exist, it sets the 'image_exists' output
          # It it doesn't exist, it leaves the 'image_exists' output unset
          gcloud artifacts docker images describe ${{ steps.parameters.outputs.image_url }} > /dev/null 2>&1 && echo "::set-output name=image_exists::true" || true

      - name: Set up QEMU
        if: ${{ ! steps.image_exists.outputs.image_exists }}
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: ${{ ! steps.image_exists.outputs.image_exists }}
        uses: docker/setup-buildx-action@v2

      - name: Configure docker to use gcloud as credential helper
        if: ${{ ! steps.image_exists.outputs.image_exists }}
        run: |
          gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev

      - name: Build custom google-compute-engine plugin
        if: ${{ ! steps.image_exists.outputs.image_exists }}
        run: |
          make build-controller-google-compute-engine-plugin

      - name: Build custom build-controller-gcp-secrets-manager-credentials-provider plugin
        if: ${{ ! steps.image_exists.outputs.image_exists }}
        run: |
          make build-controller-gcp-secrets-manager-credentials-provider-plugin

      - name: Build image and push to GCR
        if: ${{ ! steps.image_exists.outputs.image_exists }}
        uses: docker/build-push-action@v4
        with:
          context: ./Docker/controller
          push: true
          tags: ${{ steps.parameters.outputs.image_url }}
