name: swarm-agent-vm

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:

  build-linux:
    name: Linux - swarm-agent-vm
    runs-on: ubuntu-latest
    environment: 1.X
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set parameters
        id: parameters
        run: |
          SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
          IMAGE_NAME=swarm-agent-${SHORT_SHA}-linux
          echo "::set-output name=image_name::${IMAGE_NAME}"

      #- name: Setup gcloud CLI
      #  uses: google-github-actions/setup-gcloud@main
      #  with:
      #    service_account_key: ${{ secrets.GOOGLE_CLOUD_BUILD_ARTIFACT_UPLOADER_SERVICE_ACCOUNT_KEY }}
     
      - name: Setup gcloud CLI V2
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_BUILD_ARTIFACT_UPLOADER_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Test if image already exists
        id: image_exists
        run: |
          # Detect whether the image already exists
          # If it does exist, it sets the 'image_exists' output
          # It it doesn't exist, it leaves the 'image_exists' output unset
          gcloud compute images describe ${{ steps.parameters.outputs.image_name }} > /dev/null 2>&1 && echo "::set-output name=image_exists::true" || true

      - name: "Build image"
        if: ${{ ! steps.image_exists.outputs.image_exists }}
        run: |
          ./Scripts/Linux/linux-vm-image-builder.sh \
            VMs/agents/linux/swarm-agent/build.pkr.hcl \
            ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }} \
            ${{ secrets.GOOGLE_CLOUD_ZONE }} \
            ${{ steps.parameters.outputs.image_name }}

  build-windows:
    name: Windows - swarm-agent-vm
    runs-on: ubuntu-latest
    environment: 1.X
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set parameters
        id: parameters
        run: |
          SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
          IMAGE_NAME=swarm-agent-${SHORT_SHA}-windows
          echo "::set-output name=image_name::${IMAGE_NAME}"

      #- name: Setup gcloud CLI
      #  uses: google-github-actions/setup-gcloud@main
      #  with:
      #    service_account_key: ${{ secrets.GOOGLE_CLOUD_BUILD_ARTIFACT_UPLOADER_SERVICE_ACCOUNT_KEY }}
     
      - name: Setup gcloud CLI V2
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_BUILD_ARTIFACT_UPLOADER_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Test if image already exists
        id: image_exists
        run: |
          # Detect whether the image already exists
          # If it does exist, it sets the 'image_exists' output
          # It it doesn't exist, it leaves the 'image_exists' output unset
          gcloud compute images describe ${{ steps.parameters.outputs.image_name }} > /dev/null 2>&1 && echo "::set-output name=image_exists::true" || true

      - name: "Build image"
        if: ${{ ! steps.image_exists.outputs.image_exists }}
        run: |
          ./Scripts/Linux/windows-vm-image-builder.sh \
            VMs/agents/windows/swarm-agent/build.pkr.hcl \
            ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }} \
            ${{ secrets.GOOGLE_CLOUD_ZONE }} \
            ${{ steps.parameters.outputs.image_name }}
